### PR TITLE
updated chrome green version (also added dependency vulnerability fix)

### LINKED ISSUE #2216: Set Minimum Green Browser Support for Chrome to Version 78
#1869 established a baseline for browser support within the app, but with Chrome's rapid development, we need to set the floor on minimum Chrome Support. 

This update will allow a minimum Chrome Version of 78. 

We will revisit the minimum version number in the near future.

### This task is done when...
 - [ ] Chrome Browsers < version 78 will receive a receive the red browser error
 - [ ] Chrome Browsers >= version 78 will be able to use the app normally
- [ ] Someone else has confirmed the code

### PR DESCRIPTION
**Pull request by pphillips-fearless**
Set Minimum Green Browser Support for Chrome to Version 78

### This pull request changes...

- sets minimum green browser support for Chrome to version 78 (was 80)
- closes #2216 

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
~~- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented~~
~~- [ ] The change has been documented~~
~~- [ ] Associated OpenAPI documentation has been updated~~
- [x] Changelog is updated as appropriate

### CODE REVIEW

File: web/src/util/browser.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ if (browser && browser.version) {
 // well as all visual and style features to be correct.
 const browserIsGreen =
   // Current major version as of April 2020.
```
Comment (mgwalker) [inline web/src/util/browser.js:12]: Super minor: can you update this comment to note that we're intentionally supporting a slightly older Chrome and why? Just so future Paul or future Richard knows we knew Chrome 78 wasn't the most recent in April 2020. 😛
