### PR TITLE
Fix a bug where toggling the "show password" checkbox would change the user's entered password to "show password"

### LINKED ISSUE #2023: Clicking the Show Password checkbox replaces text in the password field with "Show Password"
This bug seems to have been introduced recently: When clicking the "Show Password" option on the login screen, the system replaces any text within the password field with the text "Show Password."

### This task is done when...
 - [ ] Clicking the checkbox for "Show Password" does not replace existing text
 - [ ] Clicking the checkbox for "Show Password" reveals the existing text
- [ ] Someone else has reviewed the code

### PR DESCRIPTION
**Pull request by mgwalker**
On any form with a password, toggling the "show password" checkbox would replace anything the user had entered into the password field with the literal text "Show password". This PR fixes that.

### This pull request changes...

- toggling the "show password" checkbox doesn't affect the contents of the password text box
- closes #2023

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- ~The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented~ N/A
- ~The change has been documented~ N/A
- [ ] Changelog is updated as appropriate

### CODE REVIEW

File: web/src/components/PasswordWithMeter.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ class Password extends Component {
     }
 
     return (
-      <div {...rest}>
+      <div className={className || undefined}>
```
Comment (hbillings) [inline web/src/components/PasswordWithMeter.js]: This is way more explicit, anyway.
