### PR TITLE
Fix up activity schedule dates

### LINKED ISSUE #1537: Add date to activity line and update dates in milestones for Activity Schedule Summary Table
Carried over from #1502 and #1536, the date formatting in the Activity Schedule Summary Table should be:

Screen Shot 2019-05-16 at 10 33 27 AM

- Activity date is start date – end date
- Singular date for a milestone pulled in from the planned end date entered in that subsection
- Formatting should be MM/DD/YYYY

### PR DESCRIPTION
**Pull request by mgwalker**
### This pull request changes...
- adds activity date range to activity header row
- switches milestone rows to just end date
- formats dates as `mm/dd/yyyy`
- closes #1537

### This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### This feature is done when...
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by hbillings** [comment]
Took a look at this and am assuming the thing you want my eyes on is the ziggity zaggity going on here:
Screen Shot 2019-06-11 at 6 22 32 PM

Easy enough! This is one place I'm actually okay with inline styles (shh, don't tell anyone). If we set the `width` of each of the first `tr`s (the ones with the activity titles in them) to, say, `90%`, everything should line up just fine.

**Comment by jeromeleecms** [comment]
@hbillings Inline styles? Where are your principles?! 😂 

And yes, I'm trolling a draft PR because GH e-mail notifications brought this to my attention. :trollface:

**Comment by mgwalker** [comment]
Yes, it's the ziggity zaggity, though generally speaking I don't consider it a problem: https://www.youtube.com/watch?v=je71phhaGWg

Your tip totally eliminated the ziggity zaggity, much to the dismay of dirty brass fans everywhere.  (Thank you!)

**Comment by mgwalker** [comment]
Hmm.  Not sure about that one @jeromeleecms. I'll play around with it - maybe a `white-space` style will do the trick

**Comment by hbillings** [comment]
@mgwalker You can probably address @jeromeleecms's issue by changing that suggested `90%` of mine to, like `85%` instead, heh. (Also, yes, Jerome, inline styles are a terrible dirty thing and I'm sorry.)

File: web/src/containers/ScheduleSummary.js [hunk 1]
```diff
@@ -16,29 +16,42 @@ const ScheduleSummary = ({ activities }) => (
...
-                  </th>
-                </tr>
-              </thead>
-              <tbody>
-                {milestones.map(({ end, name: milestoneName, start }) => (
+          activities.map(
+            ({ end, name: activityName, milestones, start }, i) => (
+              <table
+                key={activityName}
+                className="table-cms ds-u-margin-top--0"
```
Comment (hbillings) [inline web/src/containers/ScheduleSummary.js]: This will change with my open tables PR -- should that one get merged first and merged into this, or vice versa?

File: web/src/util/index.js [hunk 2]
```diff
@@ -179,6 +179,21 @@ export const generateKey = (() => {
...
+ * Convert a YYYY-MM-DD date string from state format into a
+ * consistent display format
+ *
+ * @param {String} date Date string from state.
+ * @returns {String} Display-formatted date string.
+ */
+export const stateDateToDisplay = date => {
+  if (date) {
+    const [year, month, day] = date.split('-');
+    return `${month}/${day}/${year}`;
```
Comment (hbillings) [inline web/src/util/index.js]: Nice clear way to obviate the regex that was being used!

File: web/src/containers/ScheduleSummary.js (hunk 1 above)
Comment (mgwalker) [reply web/src/containers/ScheduleSummary.js]: Hmm.  How much of the table will need to change, you think?  If it's just changing this class name, then it doesn't seem like it'd matter much. But if it's a big change to the table, then I think merging this one first makes more sense - to keep the contents of the PR all related.

**Comment by hbillings** [comment]
Patch incoming, @jeromeleecms.

File: web/src/containers/ScheduleSummary.js (hunk 1 above)
Comment (hbillings) [reply web/src/containers/ScheduleSummary.js]: Sorry I missed this! It'll change a few classnames, but nothing super major. Totally up to you!

Comment (mgwalker) [reply web/src/containers/ScheduleSummary.js]: For the sake of not adding work to the tables PR, let's merge that one first! I suspect changing class names here will be easier.  😄
