### PR TITLE
Fix: Deleting personnel, contractor, or expense rows triggers a budget table update

### LINKED ISSUE #645: Removing personnel, contractors, or other costs does not remove dollar amounts from budgets
The bug is the same for state personnel, contractors, or non-personnel costs.

If a user inputs dollar amounts into these fields, and then subsequently uses the X to remove the actual field (row), the dollar amounts appear to still be summed within the Summary Budget and subsequent sections. 

What should happen is that when one of the fields is removed, is that the resulting budget tables no longer sum the deleted values.

### PR DESCRIPTION
**Pull request by mgwalker**
Also fixes a bug where you couldn't add new personnel, contractor, or expense rows.  😬

Closes #645

### This pull request changes...
- deleting any of those kinds of rows will update the budget table
- deleting an activity will update the budget table
- you can add more of those kinds of rows

### This pull request is ready to merge when...
- ~Tests have been updated (and all tests are passing)~ Big tests overhaul coming soon, this will get wrapped up into that
- [ ] This code has been reviewed by someone other than the original author

### This feature is done when...
- [ ] Product has approved the experience

### CODE REVIEW

File: web/src/reducers/budget.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ const initialState = years => ({
 
 const activities = src => Object.values(src.activities.byId);
 
-const addBudgetBlocks = (into, from) => {
+const addBudgetBlocks = (into, from = { total: 0, federal: 0, state: 0 }) => {
```
Comment (mgwalker) [inline web/src/reducers/budget.js]: Handles the case where an expense type (state personnel, contractor, non-personnel) doesn't have any rows.

**Comment by mgwalker** [comment]
Hang on to this one a sec, I think we also need to handle the case when a whole activity is deleted.  😛
