### PR TITLE
Switch login page to design system

### LINKED ISSUE #1376: Apply design system styles to log in page
As detailed out in #1306, the log in page should be updated to match the CMS design system styles.

Log in page new

with incorrect email/password error state:

Log in page new - error

with empty field error state:

Log in page new error 2

### This task is done when...
 - [ ] Log in page has been updated with error states
 - [ ] Design/content have reviewed it and approve

### PR DESCRIPTION
**Pull request by hbillings**
Closes #1376.

### This pull request changes...
- Tweaks card layout format
- Factors header into its own component
- Makes password strength meter optional in password component

### This pull request is ready to merge when...
- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [x] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This feature is done when...
- [x] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by hbillings** [comment]
@lauraponce Oh! No, I should add the email-or-password error also. Thanks for reminding me!

File: web/src/containers/Login.js [hunk 1]
```diff
@@ -36,50 +37,52 @@ class Login extends Component {
...
-                onChange={this.handleChange}
-              />
+        <Header />
+        <div className="card--container">
+          <div className="ds-l-container card">
+            <div className="ds-l-row">
+              <div className="ds-l-col--1 ds-u-margin-left--auto" />
+              <div className="ds-l-col--12 ds-l-sm-col--10 ds-l-lg-col--6">
+                <h1 className="ds-h1">Log in</h1>
+                {error && error==="Unauthorized" && (
```
Comment (hbillings) [inline web/src/containers/Login.js]: This feels a little fragile to me somehow, but I wasn't sure how else to approach it.

File: web/src/containers/Login.js [hunk 2]
```diff
@@ -36,50 +37,52 @@ class Login extends Component {
...
-              <input
-                id="username"
-                type="text"
-                name="username"
-                className="input"
-                value={username}
-                onChange={this.handleChange}
-              />
+        <Header />
+        <div className="card--container">
```
Comment (hbillings) [inline web/src/containers/Login.js]: This adds the gray background. I'd really rather add a body class to the page that colors the whole page background gray because it would be more robust, but figuring out how to bubble that up seemed hard. :-p

File: web/src/containers/admin/MyAccount.js [hunk 3]
```diff
@@ -74,11 +74,11 @@ class MyAccount extends Component {
             </Link>
           </div>
         </header>
-
-        <div className="ds-l-container card">
-          <div className="ds-l-row ds-u-radius ds-u-padding-y--5">
-            <div className="ds-l-col--1 ds-u-fill--white ds-u-margin-left--auto" />
-            <div className="ds-l-col--6 ds-u-fill--white ds-u-padding-y--5">
```
Comment (hbillings) [inline web/src/containers/admin/MyAccount.js]: I made an executive decision (ha) here: I only left in the classes that governed structure. I moved rules that govern style (border radius, background color) into the CSS.

File: web/src/styles/scss/password-meter.scss [hunk 4]
```diff
@@ -2,12 +2,12 @@
 
 // This code comes from https://github.com/gladchinda/password-strength-react-demo/blob/master/src/App.css#L45
 
-.password-with-meter {
+.password-input {
```
Comment (hbillings) [inline web/src/styles/scss/password-meter.scss]: Since the meter's optional now, it seemed odd to have the classname reflect the meter disirregardless.

File: web/src/containers/Login.js (hunk 1 above)
Comment (mgwalker) [reply web/src/containers/Login.js]: In #1399 I did this by having the redux action convert the error message into a human string:

https://github.com/18F/cms-hitech-apd/pull/1399/files#diff-1af493675e4b7123516353a186f85abeR79

Then I have it reject the promise with that message.  Back in the UI components, I have them `await`/`catch` the action so they'll know when it completes or fails:

https://github.com/18F/cms-hitech-apd/pull/1399/files#diff-c6793634e433d7ad10c9c8ea93ee8005R52

But I'm not 100% in love with this pattern because it's hooking the UI directly to the actions instead of going through the state, which I think is only a problem because it's inconsistent.  However, I wasn't sure how else to handle it.  Maybe we use one big `error` state component that tracks every error message.  🤔  Not a bad approach, I think.  Maybe I'll try updating #1399 after this one is merged.

All that said...  this seems fine for now.  😛

File: web/src/components/Header.js [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+              {t('titleBasic')}
+            </Link>
+          </div>
+        </div>
+      </div>
+    </header>
+  );
+}
+
+export default Header;
```
[the remark this answers is not in the document]
Comment (hbillings) [reply web/src/components/Header.js]: It could be! I was thinking that it could at least be the header for the admin/card layout sorts of pages that we've got several of (they all seem to use the same header, anyway).

File: web/src/components/PasswordWithMeter.js [hunk 6]
```diff
@@ -81,14 +85,16 @@ Password.propTypes = {
...
+  showMeter: PropTypes.bool
 };
 
 Password.defaultProps = {
   compareTo: [],
   onChange: () => {},
   title: 'Password',
-  value: ''
+  value: '',
+  showMeter: false
```
[the remark this answers is not in the document]
Comment (hbillings) [reply web/src/components/PasswordWithMeter.js]: I stole the pattern from the feedback you gave me on adding the numbered section class ^_^
