### PR TITLE
Internal name fix for budget state data

### LINKED ISSUE #2044: [Tech debt] In the budget state data, rename "state" to "inHouse"
In the budget data, we call the rolled-up state costs `state`, but in the APD, they are called `in-house`. We should rename the internal state to match – that will make it easier to trace the data moving through the app and easier to debug/test.

The current naming is also confusing because sometimes `state` means the state's share of a cost, and sometimes it means the in-house costs. Those aren't the same thing!

### This task is done when...
 - [ ] "in-house" data is called "in-house" rather than "state"
 - [ ] state-share costs are still called "state"

### PR DESCRIPTION
**Pull request by mgwalker**
### This pull request changes...

- updates budget state to use the name `inHouse` for in-house costs rather than `state`, to be less confusing
- updates FFP tables that display in-house costs to use updated names
- closes #2044 

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- N/A ~The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented~
- N/A ~The change has been documented~
- [x] Changelog is updated as appropriate

### CODE REVIEW

File: web/src/reducers/budget.js [hunk 1]
```diff
@@ -458,18 +458,19 @@ const buildBudget = incomingBigState => {
       const quarterlyFFP = newState.federalShareByFFYQuarter[ffpSource];
 
       ['contractors', 'expenses', 'statePersonnel'].forEach(prop => {
-        const propCostType = prop === 'contractors' ? 'contractors' : 'state';
+        const ffpType = prop === 'contractors' ? 'contractors' : 'state';
```
Comment (hbillings) [inline web/src/reducers/budget.js]: Does `state` in this instance refer to something different than the `state` that `inHouse` replaced?

Comment (mgwalker) [reply web/src/reducers/budget.js]: Kind of yes, kind of now. It's the same type of information, but this one comes from the user input rather than the budget calculations. There's #2066 to finish out the change, but the two seemed big enough to be separate PRs.
